#!/usr/bin/env bash

SRC="$1"

if [ -z "$SRC" ]; then
    echo "BUILD_ERROR: Missing source"
    exit 1
fi

NAME=$(basename $SRC)
NAME="${NAME%.*}"
OUT_DIR="test/bin"
DST=$OUT_DIR/$NAME

RAYLIB="/opt/homebrew/opt/raylib"
COMPILATION_FLAGS="-std=c++20 -O2 -flto"
WARNING_FLAGS="-Wall -Wextra"
LINK_FLAGS="-I$RAYLIB/include -L$RAYLIB/lib -lraylib -framework OpenGL -framework IOKit -framework Cocoa"

RUN_AFTER_BUILD=0
if [ "$2" == "-r" ] || [ "$2" == "--run" ]; then
    RUN_AFTER_BUILD=1
fi

mkdir -p $OUT_DIR
CMD="clang++ -o $DST $SRC $COMPILATION_FLAGS $WARNING_FLAGS $LINK_FLAGS"
echo "BUILD: $CMD"
$CMD

if [ $? -eq 0 ]; then
    echo "BUILD: Compiled $DST"
    if [ $RUN_AFTER_BUILD -eq 1 ]; then
        $DST
    fi
fi
