#!/usr/bin/env bash

OUT_DIR="bin"
SRC_DIR="src"

SOURCES=$(fd . -e cpp -tf $SRC_DIR)
DST=$OUT_DIR/main

RAYLIB="/opt/homebrew/opt/raylib"
COMPILATION_FLAGS="-std=c++20 -O2 -flto"
WARNING_FLAGS="-Wall -Wextra"
LINK_FLAGS="-I$RAYLIB/include -L$RAYLIB/lib -lraylib -framework OpenGL -framework IOKit -framework Cocoa"

RUN_AFTER_BUILD=0
if [ "$1" == "-r" ] || [ "$1" == "--run" ]; then
    RUN_AFTER_BUILD=1
fi

mkdir -p $OUT_DIR
CMD="clang++ -o $DST $SOURCES $COMPILATION_FLAGS $WARNING_FLAGS $LINK_FLAGS"
echo "BUILD: $CMD"
$CMD

if [ $? -eq 0 ]; then
    echo "BUILD: Compiled $DST"
    if [ $RUN_AFTER_BUILD -eq 1 ]; then
        $DST
    fi
fi
